package com.rhodes.tv

/**
 * 频道分组重分类: 把上游杂乱、且组内关系不大的 group-title 归一到 12 个稳定大类。
 * 规则: 名称关键词优先(见 PRIORITY 顺序), 无语义歧义的上游组直接强制定类(FORCE), 其余用 HINT 兜底。
 * 词表与 temp/iptv_research/classify_proto.py 同源(改一处要同步另一处)。
 */
object GroupRules {

    /** 分组展示顺序 */
    val ORDER = listOf(
            "央视频道",
            "卫视频道",
            "地方频道",
            "港澳台频道",
            "影视综艺",
            "体育频道",
            "少儿动画",
            "新闻财经",
            "纪录人文",
            "音乐戏曲",
            "国际频道",
            "其他频道",
        )

    private val LABEL = mapOf(
        "cctv" to "央视频道",
        "sat" to "卫视频道",
        "local" to "地方频道",
        "hmt" to "港澳台频道",
        "film" to "影视综艺",
        "sports" to "体育频道",
        "kids" to "少儿动画",
        "news" to "新闻财经",
        "doc" to "纪录人文",
        "music" to "音乐戏曲",
        "intl" to "国际频道",
        "other" to "其他频道"
    )

    private val PRIORITY = listOf(
            "cctv",
            "hmt",
            "sat",
            "sports",
            "kids",
            "film",
            "news",
            "intl",
            "local",
            "doc",
            "music",
        )

    /** 关键词表(全部为子串匹配; 匹配时同时尝试原文与全大写) */
    private val K = mapOf(
        "cctv" to listOf(
                "CCTV",
                "央视",
                "中央电视",
                "总台",
                "CGTN",
                "中国环球电视网",
                "中学生频道",
        ),
        "hmt" to listOf(
                "翡翠",
                "明珠",
                "无线",
                "TVB",
                "HOY",
                "VIUTV",
                "ViuTV",
                "香港",
                "澳门",
                "澳视",
                "莲花",
                "MACAU",
                "台湾",
                "台视",
                "中视",
                "华视",
                "民视",
                "东森",
                "三立",
                "TVBS",
                "中天",
                "纬来",
                "龙华",
                "龙祥",
                "八大",
                "公视",
                "寰宇",
                "凤凰",
                "RTHK",
                "港台电视",
                "开电视",
                "NowTV",
                "J2",
                "Viu",
                "大爱",
                "人间卫视",
                "非凡",
                "年代",
                "高点",
                "澳亚",
                "美亚",
        ),
        "sat" to listOf(
                "卫视",
        ),
        "sports" to listOf(
                "体育",
                "足球",
                "篮球",
                "NBA",
                "英超",
                "西甲",
                "德甲",
                "意甲",
                "法甲",
                "中超",
                "CBA",
                "赛事",
                "高尔夫",
                "网球",
                "羽毛球",
                "乒乓",
                "台球",
                "搏击",
                "拳击",
                "电竞",
                "运动",
                "健身",
                "赛车",
                "摩托",
                "冰雪",
                "排球",
                "游泳",
                "田径",
                "棋",
                "钓鱼",
                "武术",
                "跆拳",
                "解说",
        ),
        "kids" to listOf(
                "少儿",
                "卡通",
                "动漫",
                "动画",
                "儿童",
                "宝贝",
                "亲子",
                "优漫",
                "KAKU",
                "幼教",
                "小伶",
                "巧虎",
                "EBS",
                "金鹰",
                "童",
                "萌",
                "龙珠",
                "柯南",
                "宝可梦",
                "哆啦A梦",
                "喜羊羊",
                "灌篮高手",
                "中华小当家",
                "海绵宝宝",
                "猫和老鼠",
                "熊出没",
                "奥特曼",
                "火影",
                "海贼",
                "米老鼠",
                "变形金刚",
                "数码宝贝",
                "小猪佩奇",
                "汪汪队",
        ),
        "film" to listOf(
                "电影",
                "影视",
                "剧场",
                "影院",
                "电视剧",
                "片场",
                "剧集",
                "美剧",
                "韩剧",
                "港剧",
                "泰剧",
                "日剧",
                "经典",
                "怀旧",
                "好莱坞",
                "CHC",
                "春晚",
                "综艺",
                "小品",
                "相声",
                "喜剧",
                "邵氏",
                "埋堆堆",
                "连续剧",
                "古装",
                "武侠",
                "玄幻",
                "偶像",
                "刑侦",
                "悬疑",
                "情感",
                "影剧",
        ),
        "news" to listOf(
                "财经",
                "经济",
                "股市",
                "证券",
                "资讯",
                "第一财经",
                "CNBC",
                "Bloomberg",
                "东方财经",
                "时事",
                "议会",
        ),
        "intl" to listOf(
                "国际",
                "海外",
                "NHK",
                "BBC",
                "CNN",
                "KBS",
                "MBC",
                "SBS",
                "ABC",
                "CBS",
                "NBC",
                "FOX",
                "RT",
                "DW",
                "ARTE",
                "France",
                "Aljazeera",
                "Al-Jazeera",
                "Arirang",
                "Bloomberg",
                "Sky",
                "Euro",
                "TRT",
                "RAI",
                "TV5",
                "澳大利亚",
                "美国",
                "英国",
                "法国",
                "德国",
                "俄罗斯",
                "日本",
                "韩国",
                "印度",
                "越南",
                "泰国",
                "意大利",
                "西班牙",
                "葡萄牙",
                "阿拉伯",
                "土耳其",
                "以色列",
                "加拿大",
                "巴西",
                "阿根廷",
                "非洲",
                "欧洲",
                "美洲",
                "亚洲",
                "英语",
                "双语",
                "塞尔维亚",
                "Newsmax",
                "Wion",
                "astro",
                "八度空间",
                "新加坡",
                "mediacorp",
        ),
        "local" to listOf(
                "北京",
                "上海",
                "天津",
                "重庆",
                "河北",
                "山西",
                "辽宁",
                "吉林",
                "黑龙江",
                "江苏",
                "浙江",
                "安徽",
                "福建",
                "江西",
                "山东",
                "河南",
                "湖北",
                "湖南",
                "广东",
                "广西",
                "海南",
                "四川",
                "贵州",
                "云南",
                "陕西",
                "甘肃",
                "青海",
                "宁夏",
                "新疆",
                "西藏",
                "内蒙古",
                "延边",
                "伊犁",
                "大理",
                "西双版纳",
                "红河",
                "文山",
                "楚雄",
                "凉山",
                "甘孜",
                "阿坝",
                "康巴",
                "广州",
                "深圳",
                "珠海",
                "汕头",
                "佛山",
                "韶关",
                "湛江",
                "肇庆",
                "江门",
                "茂名",
                "惠州",
                "梅州",
                "汕尾",
                "河源",
                "阳江",
                "清远",
                "东莞",
                "中山",
                "潮州",
                "揭阳",
                "云浮",
                "南宁",
                "桂林",
                "柳州",
                "北海",
                "钦州",
                "贵港",
                "玉林",
                "百色",
                "贺州",
                "河池",
                "来宾",
                "崇左",
                "海口",
                "三亚",
                "儋州",
                "琼海",
                "文昌",
                "万宁",
                "成都",
                "自贡",
                "攀枝花",
                "泸州",
                "德阳",
                "绵阳",
                "广元",
                "遂宁",
                "内江",
                "乐山",
                "南充",
                "眉山",
                "宜宾",
                "广安",
                "达州",
                "雅安",
                "巴中",
                "资阳",
                "西昌",
                "萧山",
                "萧山",
                "餘姚",
                "余姚",
                "萬州",
                "万州",
                "三峡",
                "贵阳",
                "六盘水",
                "遵义",
                "安顺",
                "毕节",
                "铜仁",
                "凯里",
                "都匀",
                "兴义",
                "万州",
                "昆明",
                "曲靖",
                "玉溪",
                "保山",
                "昭通",
                "丽江",
                "普洱",
                "临沧",
                "拉萨",
                "日喀则",
                "昌都",
                "林芝",
                "西安",
                "铜川",
                "宝鸡",
                "咸阳",
                "渭南",
                "延安",
                "汉中",
                "榆林",
                "安康",
                "商洛",
                "兰州",
                "嘉峪关",
                "金昌",
                "白银",
                "天水",
                "武威",
                "张掖",
                "平凉",
                "酒泉",
                "庆阳",
                "定西",
                "陇南",
                "西宁",
                "海东",
                "银川",
                "石嘴山",
                "吴忠",
                "固原",
                "中卫",
                "乌鲁木齐",
                "克拉玛依",
                "吐鲁番",
                "哈密",
                "昌吉",
                "伊宁",
                "阿克苏",
                "喀什",
                "和田",
                "库尔勒",
                "呼和浩特",
                "包头",
                "乌海",
                "赤峰",
                "通辽",
                "鄂尔多斯",
                "呼伦贝尔",
                "巴彦淖尔",
                "乌兰察布",
                "沈阳",
                "大连",
                "鞍山",
                "抚顺",
                "本溪",
                "丹东",
                "锦州",
                "营口",
                "阜新",
                "辽阳",
                "盘锦",
                "铁岭",
                "朝阳",
                "葫芦岛",
                "长春",
                "四平",
                "辽源",
                "通化",
                "白山",
                "松原",
                "白城",
                "延吉",
                "哈尔滨",
                "齐齐哈尔",
                "鸡西",
                "鹤岗",
                "双鸭山",
                "大庆",
                "伊春",
                "佳木斯",
                "七台河",
                "牡丹江",
                "黑河",
                "绥化",
                "石家庄",
                "唐山",
                "秦皇岛",
                "邯郸",
                "邢台",
                "保定",
                "张家口",
                "承德",
                "沧州",
                "廊坊",
                "衡水",
                "太原",
                "大同",
                "阳泉",
                "长治",
                "晋城",
                "朔州",
                "晋中",
                "运城",
                "忻州",
                "临汾",
                "吕梁",
                "郑州",
                "开封",
                "洛阳",
                "平顶山",
                "安阳",
                "鹤壁",
                "新乡",
                "焦作",
                "濮阳",
                "许昌",
                "漯河",
                "三门峡",
                "南阳",
                "商丘",
                "信阳",
                "周口",
                "驻马店",
                "武汉",
                "黄石",
                "十堰",
                "宜昌",
                "襄阳",
                "鄂州",
                "荆门",
                "孝感",
                "荆州",
                "黄冈",
                "咸宁",
                "随州",
                "长沙",
                "株洲",
                "湘潭",
                "衡阳",
                "邵阳",
                "岳阳",
                "常德",
                "张家界",
                "益阳",
                "郴州",
                "永州",
                "怀化",
                "娄底",
                "南昌",
                "景德镇",
                "萍乡",
                "九江",
                "新余",
                "鹰潭",
                "赣州",
                "吉安",
                "宜春",
                "抚州",
                "上饶",
                "南京",
                "无锡",
                "徐州",
                "常州",
                "苏州",
                "南通",
                "连云港",
                "淮安",
                "盐城",
                "扬州",
                "镇江",
                "泰州",
                "宿迁",
                "杭州",
                "宁波",
                "温州",
                "嘉兴",
                "湖州",
                "绍兴",
                "金华",
                "衢州",
                "舟山",
                "台州",
                "丽水",
                "合肥",
                "芜湖",
                "蚌埠",
                "淮南",
                "马鞍山",
                "淮北",
                "铜陵",
                "安庆",
                "黄山",
                "滁州",
                "阜阳",
                "宿州",
                "六安",
                "亳州",
                "池州",
                "宣城",
                "福州",
                "厦门",
                "莆田",
                "三明",
                "泉州",
                "漳州",
                "南平",
                "龙岩",
                "宁德",
                "济南",
                "青岛",
                "淄博",
                "枣庄",
                "东营",
                "烟台",
                "潍坊",
                "济宁",
                "泰安",
                "威海",
                "日照",
                "临沂",
                "德州",
                "聊城",
                "滨州",
                "菏泽",
                "上虞",
                "义乌",
                "慈溪",
                "余姚",
                "诸城",
                "寿光",
                "海宁",
                "桐乡",
                "平湖",
                "嵊州",
                "新昌",
                "温岭",
                "临海",
                "瑞安",
                "乐清",
                "苍南",
                "象山",
                "宁海",
                "奉化",
                "富阳",
                "临安",
                "建德",
                "淳安",
                "武进",
                "江阴",
                "宜兴",
                "溧阳",
                "金坛",
                "丹阳",
                "句容",
                "江都",
                "仪征",
                "高邮",
                "兴化",
                "靖江",
                "泰兴",
                "如皋",
                "海门",
                "启东",
                "海安",
                "东台",
                "大丰",
                "邳州",
                "新沂",
                "沭阳",
                "泗阳",
                "盱眙",
                "金湖",
                "涟水",
                "灌云",
                "东海",
                "郯城",
                "兰陵",
                "沂水",
                "平邑",
                "费县",
                "莒南",
                "临沭",
                "曹县",
                "单县",
                "郓城",
                "鄄城",
                "梁山",
                "汶上",
                "泗水",
                "邹城",
                "滕州",
                "微山",
                "鱼台",
                "金乡",
                "嘉祥",
                "钱江",
                "南国",
                "anhui",
                "hebei",
                "hunan",
                "hubei",
                "henan",
                "jiangsu",
                "zhejiang",
                "guangdong",
                "guangxi",
                "sichuan",
                "yunnan",
                "guizhou",
                "shandong",
                "shanxi",
                "shaanxi",
                "fujian",
                "jiangxi",
                "gansu",
                "qinghai",
                "ningxia",
                "xinjiang",
                "xizang",
                "tibet",
                "neimonggol",
                "liaoning",
                "jilin",
                "heilongjiang",
                "hainan",
                "chongqing",
                "tianjin",
                "beijing",
                "shanghai",
                "harbin",
                "guangzhou",
                "lanzhou",
                "qingdao",
                "qtv",
                "chifeng",
                "chuxiong",
                "siping",
                "anshun",
                "wanzhou",
                "kangba",
                "hohhot",
                "urumqi",
                "kunming",
                "nanning",
                "fuzhou",
                "xiamen",
                "shenzhen",
                "dalian",
                "suzhou",
                "wuxi",
                "ningbo",
                "wenzhou",
                "nanchang",
                "changsha",
                "zhengzhou",
                "jinan",
                "taiyuan",
                "hefei",
                "guiyang",
                "haikou",
                "sanya",
                "yantai",
                "weifang",
                "linyi",
                "huizhou",
                "jiangmen",
                "zhaoqing",
                "shantou",
                "foshan",
                "dongguan",
                "zhongshan",
                "zhuhai",
                "公共",
                "都市",
                "综合",
                "新闻综合",
                "电视台",
                "有线",
                "文旅",
                "民生",
                "生活资讯",
                "影视娱乐",
                "经济生活",
                "科教",
                "农村",
                "城市",
                "一套",
                "二套",
                "三套",
                "四套",
                "新闻频道",
                "文化娱乐",
                "文化生活",
                "文化影院",
                "生活频道",
                "影视生活",
        ),
        "doc" to listOf(
                "纪录",
                "纪实",
                "人文",
                "探索",
                "地理",
                "科学",
                "历史",
                "自然",
                "动物",
                "Discovery",
                "国家地理",
                "考古",
                "文化",
                "讲堂",
                "百家",
                "人与自然",
                "地球",
                "宇宙",
                "风光",
                "全景",
                "景区",
                "旅游",
                "世界遗产",
                "博物馆",
                "观景",
                "实景",
                "航拍",
                "直播中国",
                "生态环境",
                "特产",
        ),
        "music" to listOf(
                "音乐",
                "MV",
                "演唱会",
                "歌曲",
                "MTV",
                "咪咕",
                "戏曲",
                "曲艺",
                "京剧",
                "评剧",
                "越剧",
                "豫剧",
                "黄梅戏",
                "秦腔",
                "昆曲",
                "音乐会",
                "歌舞",
        ),
    )

    /** 多词短语(不能按空格拆开, 否则 "Dragon TV" 会命中 "TV") */
    private val PHRASES = mapOf(
        "hmt" to listOf(
                "NOW NEWS",
                "NOW TV",
                "NOW NEWS",
                "NOW TV",
                "TVB",
        ),
        "sat" to listOf(
                "DRAGON TV",
                "SATELLITE",
        ),
        "intl" to listOf(
                "AL JAZEERA",
                "ALJAZEERA",
                "FOX NEWS",
                "FOX WEATHER",
                "RT ",
        ),
    )

    /** 语义无歧义的上游分组 -> 大类(先于名称规则生效) */
    private val FORCE = mapOf(
        "直播中国" to "doc",
        "春晚频道" to "film",
        "历年春晚" to "film",
        "埋堆堆频道" to "film",
        "虎牙影视" to "film",
        "斗鱼影视" to "film",
        "动画频道" to "kids",
        "儿童频道" to "kids",
        "电影频道" to "film",
        "电视剧频道" to "film",
        "音乐频道" to "music",
        "体育频道" to "sports",
        "国际频道" to "intl",
        "国际时事" to "intl",
        "央视IPV4" to "cctv",
        "央视频道" to "cctv",
        "卫视频道" to "sat",
        "少儿" to "kids",
        "电视剧" to "film",
        "电影" to "film",
        "体育" to "sports",
    )

    /** 上游分组兜底(名称规则都没命中时用) */
    private val HINT = mapOf(
        "直播中国" to "doc",
        "地方频道" to "local",
        "国际时事" to "intl",
        "港澳代理" to "hmt",
        "春晚频道" to "film",
        "埋堆堆频道" to "film",
        "虎牙影视" to "film",
        "斗鱼影视" to "film",
        "音乐频道" to "music",
        "体育频道" to "sports",
        "动画频道" to "kids",
        "儿童频道" to "kids",
        "电影频道" to "film",
        "电视剧频道" to "film",
        "纪录频道" to "doc",
        "国际频道" to "intl",
        "央视频道" to "cctv",
        "央视IPV4" to "cctv",
        "卫视频道" to "sat",
        "电视剧" to "film",
        "电影" to "film",
        "少儿" to "kids",
        "体育" to "sports",
    )

    private val K_UP = K.mapValues { e -> e.value.map { it.uppercase() } }
    private val PH_UP = PHRASES.mapValues { e -> e.value.map { it.uppercase() } }

    /** 画质/离线标记: (1080p) [Not 24/7] 之类, 显示与归一化时都去掉 */
    private val QUALITY = Regex(
        "[（(][^）)]*(1080|720|576|2160|4K|HD|高清|超清|FHD|fps)[^）)]*[）)]|[\\[［][^\\]］]*(Not 24/7|1080|720|576|2160|4K|HD|fps)[^\\]］]*[\\]］]",
        RegexOption.IGNORE_CASE
    )

    /** 合并同名频道的归一化键: 去画质后缀、统一 CCTV 写法、去空格 */
    fun normName(n: String): String {
        val s = QUALITY.replace(n, "").replace("CCTV-", "CCTV").replace("CCTV_", "CCTV")
        return s.replace(Regex("\\s+"), "").trim().lowercase()
    }

    /** 展示名: 只去掉画质/离线标记 */
    fun cleanName(n: String): String {
        val s = QUALITY.replace(n, "").replace("  ", " ").trim()
        return s.ifEmpty { n.trim() }
    }

    private fun hit(s: String, kws: List<String>): Boolean = kws.any { it.isNotEmpty() && s.contains(it) }

    /** 上游组名归一化: 只留中英文数字(与原型 classify_proto.py 的 re.sub(r'[^\\w\\u4e00-\\u9fa5]','',up) 等价) */
    private fun upKey(up: String): String = up.replace(Regex("[^\\w\\u4e00-\\u9fa5]"), "")

    /** 主入口: 返回 12 大类之一。顺序与原型严格一致: FORCE 强制定类 -> 名称关键词(按 PRIORITY) -> HINT 兜底 -> 其他 */
    fun classify(name: String, upstreamGroup: String): String {
        val uk = upKey(upstreamGroup)
        FORCE[uk]?.let { return LABEL[it] ?: "其他频道" }
        val up = name.uppercase()
        for (k in PRIORITY) {
            if (hit(name, K[k]!!) || hit(up, K_UP[k]!!) || hit(up, PH_UP[k] ?: emptyList())) {
                return LABEL[k] ?: "其他频道"
            }
        }
        HINT[uk]?.let { return LABEL[it] ?: "其他频道" }
        return "其他频道"
    }

    /** 分组排序权重(用于主界面标签栏顺序) */
    fun orderOf(group: String): Int {
        val i = ORDER.indexOf(group)
        return if (i < 0) ORDER.size else i
    }
}
